### ISSUE TITLE
Update from 1.4.3 to 2.0.4 via brew does not work

### ISSUE THREAD

**Issue by sisyphosloughs** [iglance/iGlance#122]
**Describe the bug🐛**
I followed the instructions in the warning message. Unfortunatly the Version is not able to upgrade iGlance on my Mac (macOS 10.15.3 (19D76)).

**To Reproduce**

1. Get infomations about the cask **iglance**:
```
▶ brew cask info iglance
iglance: 2.0.4 (auto_updates)
https://github.com/iglance/iGlance
/usr/local/Caskroom/iglance/1.4.3 (121B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/iglance.rb
==> Name
iGlance
==> Artifacts
iGlance.app (App)
```
2. I copy and pated the command from the iGlance-window:
```
▶ brew update && brew cask upgrade
Already up-to-date.
==> No Casks to upgrade
```
3. I reproduced step 1:
```
▶ brew cask info iglance          
iglance: 2.0.4 (auto_updates)
https://github.com/iglance/iGlance
/usr/local/Caskroom/iglance/1.4.3 (121B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/iglance.rb
==> Name
iGlance
==> Artifacts
iGlance.app (App)
```
4. I restartet the computer. The iGlance-update massage pop ups again.

**Expected behavior**
Upgraded iGlance or a link for a more detailed upgrad description.

**Screenshots (Optional)**

<img width="571" alt="iGance_InstructionsAndResult" src="https://user-images.githubusercontent.com/11442081/78453681-9a58c380-7693-11ea-8bfa-9114f24d8b2e.png">

**Desktop (please complete the following information):**

- MacOS Version: macOS 10.15.3 (19D76)
- Version of the app: 1.4.3 (121B)

**Log**
Please activate `Advanced Logging` in the settings, restart the app and perform the steps to reproduce the bug.

I cannot find that option.

<img width="397" alt="iGlance_NoLoggingInSetting" src="https://user-images.githubusercontent.com/11442081/78453660-6ed5d900-7693-11ea-899a-5eca85df9cd2.png">

After the bug occurred, please close the app completely (i.e. by opening the app window and pressing `CMD+Q`).
Please take the latest log file from `~/Library/Logs/iGlance/` and upload it here.

**Comment by D0miH** [comment]
Hey @sisyphosloughs,

sorry for the inconvenience. I am not sure why this is happening. 
This might happen due to introducing auto updating to iGlance in version 2.0.
Did you try to uninstall iGlance and reinstall it using brew?

**Comment by sisyphosloughs** [comment]
@D0miH,
Thank you very much, that worked:
```
▶ brew cask uninstall iglance
==> Uninstalling Cask iglance
==> Backing App 'iGlance.app' up to '/usr/local/Caskroom/iglance/1.4.3/iGlance.a
==> Removing App '/Applications/iGlance.app'.
==> Purging files for version 1.4.3 of Cask iglance

~
▶ brew cask install iglance
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
terragrunt      vulkan-headers  wxmaxima        xmrig           yaz

==> Downloading https://github.com/iglance/iglance/releases/download/v2.0.4/iGla
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'iglance'.
==> Installing Cask iglance
==> Moving App 'iGlance.app' to '/Applications/iGlance.app'.
🍺  iglance was successfully installed!

~
▶ brew cask info iglance
iglance: 2.0.4 (auto_updates)
https://github.com/iglance/iGlance
/usr/local/Caskroom/iglance/2.0.4 (121B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/iglance.rb
==> Name
iGlance
==> Artifacts
iGlance.app (App)
```
So that worked. From my point of view, I'd only change the text in the information window, because the suggestes procedure does not work. Something like 'uninstall and install' would be enough.

Of course I have lost my settings, but on the other hand, the tool is so handy (what I really like), that users can configure in less then 2 minutes.

The remaining battery time is great improvement!

Thank you guys!

**Comment by D0miH** [comment]
Glad it worked:)
