### ISSUE TITLE
Memory bug (or question if I'm misinterpreting)

### ISSUE THREAD

**Issue by revonoc** [iglance/iGlance#123]
**Describe the bug🐛**
Memory numbers on bar when clicked on do not add up to my total memory (8GB). For instance, Activity Monitor gives me 2 gigs free right now, iGlance just 0.1 - is this a bug?

**To Reproduce**
Click on memory bar in menubar

**Screenshots (Optional)**
<img width="203" alt="Screen Shot 2020-04-04 at 16 53 43" src="https://user-images.githubusercontent.com/23653752/78461223-20293e80-7695-11ea-82ae-bd1f0bd04205.png">

**Desktop (please complete the following information):**

- MacOS Version: 10.15.4
- Version of the app: 2.0.4

**Log**
Please activate `Advanced Logging` in the settings, restart the app and perform the steps to reproduce the bug.
After the bug occurred, please close the app completely (i.e. by opening the app window and pressing `CMD+Q`).
Please take the latest log file from `~/Library/Logs/iGlance/` and upload it here.
[io.github.iglance.iGlance 2020-04-04--20-37-28-877.log](https://github.com/iglance/iGlance/files/4432515/io.github.iglance.iGlance.2020-04-04--20-37-28-877.log)

**Comment by D0miH** [comment]
Hey @revonoc,

you are totally correct in your assumption that this is a bug. So thanks for reporting it!👍🏼
It will be fixed in the next version of the app:)

**Comment by revonoc** [comment]
Amazing, thanks so much!
