### ISSUE TITLE
Menubar items stop refreshing after sleeping

### ISSUE THREAD

**Issue by revonoc** [iglance/iGlance#125]
**Describe the bug🐛**
Netowork module displays 0KB/s up and down despite being online and browsing/watching videos/Zooming

**To Reproduce**
Not entirely sure - seems to have happened when i woke my computer from sleep or switched to VPN

**Expected behavior**
Shows traffic numbers

**Screenshots (Optional)**
<img width="96" alt="Screen Shot 2020-04-05 at 23 13 25" src="https://user-images.githubusercontent.com/23653752/78520292-0cb0cd00-7794-11ea-8725-360bfdd2f3c5.png">

**Desktop (please complete the following information):**

- MacOS Version: 10.15.4
- Version of the app: 2.0.4

**Log**
Couldn't log it, had logging off when it happened sadly, will try to replicate

**Comment by D0miH** [comment]
Oh, this is strange!
Could you upload the log file that was created when the bug occurred? Even though you haven't had "Advanced Logging" enabled errors should still be logged. The log files have their creation date in their name and each 24 hours a new log file is created. 

Would be a huge help if you provide the error log :)

**Comment by sercant** [comment]
In my case, everything (network, memory, cpu, temperature) gets stuck. I have noticed that it usually happens after waking up from a long sleep.

Logs file has this line only:

```log
20-04-07 16:55:48:568 Error: [UserSettings:123]: Could not decode the saved user settings
```

**Comment by revonoc** [comment]
> In my case, everything (network, memory, cpu, temperature) gets stuck. I have noticed that it usually happens after waking up from a long sleep.
> 
> Logs file has this line only:
> 
> ```
> 20-04-07 16:55:48:568 Error: [UserSettings:123]: Could not decode the saved user settings
> ```

I've started to notice the same thing that everything is locking, I have to restart the app and everything works. Both wake-ups and network changes I think?

**Comment by D0miH** [comment]
Hey guys,
so I have an idea what could cause this bug. I will check it out in the next few days :)

**Comment by nbigaouette** [comment]
This morning the I had the problem, I'm uploading the log file.

I'm not seeing anything useful in it though. It looks like it stopped logging yesterday night?

In any case, here it is:
[io.github.iglance.iGlance 2020-04-15--23-50-17-633.log.gz](https://github.com/iglance/iGlance/files/4487768/io.github.iglance.iGlance.2020-04-15--23-50-17-633.log.gz)

**Comment by nbigaouette** [comment]
I've went to the app's settings (it was still responsive) and changed the refresh rate (to 2 seconds). This "unfroze" iglance which started logging again. I'm attaching the updated file.

[io.github.iglance.iGlance 2020-04-15--23-50-17-633-after-refresh.log.gz](https://github.com/iglance/iGlance/files/4487781/io.github.iglance.iGlance.2020-04-15--23-50-17-633-after-refresh.log.gz)

**Comment by D0miH** [comment]
Hey guys,

so I looked into it and I think the problem is that the memory of the timer that is responsible for refreshing the app every <time_interval> seconds is freed and therefore the app frozen. 
I will implement a fix and will release a new version that includes some other bug fixes

**Comment by ChillarAnand** [comment]
Thanks, @D0miH for the quick fix.

I have upgraded to 2.0.5. Still, I am facing the same issue. When mac goes to sleep and wakes up, iGlance stays in a frozen state.

**Comment by D0miH** [comment]
hmm this is strange. 
The steps to reproduce are still the same? Does this only occur on sleeping or also on changing the network as @revonoc described? How long is your computer (roughly) sleeping when this bug occurs? Because when I click the apple logo and select "sleep" the app is still refreshing after waking the machine up 30 seconds later.

**Comment by ChillarAnand** [comment]
Switching network is not causing any problem. When mac sleeps for a while and wakes up,  I have faced the issue. 

Will try to reproduce and provide exact steps.

**Comment by nbigaouette** [comment]
I've updated to 2.0.5 and though the issue was fixed, but it just happened again. I'm not even sure it happened during a suspend/resume cycle as I'm using the computer. I could be wrong though, but I though it was working when I started working this morning. I had to switch the refresh rate to make it work again...

**Comment by D0miH** [comment]
Ok, so I looked into it and I think the problem is now solved by moving the whole refreshing of the menu bar items into a separate background thread. I couldn't reproduce it with this fix and hope that the issue is now resolved.
