### ISSUE TITLE
Fan speed is 0 RPM on 2015 MBP 13"

### ISSUE THREAD

**Issue by aptagood** [iglance/iGlance#126]
**Describe the bug🐛**
The Fan module reports 0 RPM all the time.

**To Reproduce**
Check the box to Show Fan Speed in iGlance Settings

**Expected behavior**
Fan should show a value >0.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/11530868/78732489-9af19400-78f7-11ea-80ec-83270db8c40b.png)

**Desktop (please complete the following information):**
- MacOS Version: 10.13.6
- Version of the app: 2.0.4

**Log**
[io.github.iglance.iGlance 2020-04-08--00-21-00-420.log](https://github.com/iglance/iGlance/files/4447610/io.github.iglance.iGlance.2020-04-08--00-21-00-420.log)

**Comment by D0miH** [comment]
Hey @aptagood,
I don't think that this is a bug. It can be the case that the fans on a 13 inch machine don't spin at  all when the cpu is not under high load. 
You could test this theory by stressing the cpu a bit and then check if the fans are spinning?

**Comment by aptagood** [comment]
You were totally correct.  Eventually the fans kicked in and RPM meter showed > 0.
Thanks!
