### ISSUE TITLE
The logo is really ugly and doesn't fit in with the rest of the app :(

### ISSUE THREAD

**Issue by caecebo** [iglance/iGlance#129]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want a logo that speaks the same language the rest of the app does. 

**Describe alternatives you've considered**
I am not sure if this applies.

**Additional context**
![iGlance_logo_black](https://user-images.githubusercontent.com/62819080/79181537-2ecccf80-7dd2-11ea-9489-82ef54710792.png)
![iGlance_Preview](https://user-images.githubusercontent.com/62819080/79181572-43a96300-7dd2-11ea-99c8-de91d59db694.jpg)

**Comment by caecebo** [comment]
why do you not care about your app being beautiful and getting ruined by a horrible blue futura logo??

:((( im sure someone will care

it's not very inviting to download the app because it looks like what a small minecraft plugin developer would make to replace a logo on the spigot forums

**Comment by D0miH** [comment]
I do care about the app! If you have constructive feedback I am absolutely open to change or improve the logo. But just criticising (imo in a harsh way) is not helpful and therefore I closed the issue.
