### ISSUE TITLE
CPU temperature only works when plugged in

### ISSUE THREAD

**Issue by wrongsyntax** [iglance/iGlance#13]
**Describe the bug**
CPU temperature only displays properly when the Macbook is plugged in and charging

**To Reproduce**
1. Enable CPU Temperature
2. Plug the charger in and see the CPU temp
3. Unplug charger
4. See -1ºC

**Expected behavior**
The CPU temp to work even if the Macbook is not charging

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version: 1.2.2

**Comment by edilsonborges** [comment]
Couldn't reproduce the error here, Uzair. Have you try this behavior on this?
- previous version (1.2.1)
- check another app for temperature indicator (Fanny - https://github.com/DanielStormApps/Fanny)

**Comment by D0miH** [comment]
Hi Uzair,

sorry to hear that the app is not working. 
What machine are you using? 

Another solution might be to reset the SMC. How to do that, you can read [her](https://support.apple.com/en-us/HT201295).

**Comment by wrongsyntax** [comment]
I’m using a MacBook Air from last year

**Comment by D0miH** [comment]
@wrongsyntax Ok, so I looked into the code and couldn't find anything which could lead to your described behaviour. 
Did you try to reset your SMC?
