### ISSUE TITLE
iGlance stops refreshing after resume

### ISSUE THREAD

**Issue by nbigaouette** [iglance/iGlance#130]
**Describe the bug🐛**

iGlance 2.0.4 will stop refreshing its widget after a resume from suspend.

Going in the preferences and chaning the refresh rate will make it work again.

**To Reproduce**

1. Launch iGlance
2. Suspend the laptop
3. Resume the laptop

**Expected behavior**

iGlance should continue to refresh its widget after resume.

**Screenshots (Optional)**

N/A

**Desktop (please complete the following information):**

- MacOS Version: Catalina 10.15.4 (19E287) (macBook Pro 15" 2017)
- Version of the app: 2.0.4

**Log**

TODO: Will upload the logs later.

Please activate `Advanced Logging` in the settings, restart the app and perform the steps to reproduce the bug.
After the bug occurred, please close the app completely (i.e. by opening the app window and pressing `CMD+Q`).
Please take the latest log file from `~/Library/Logs/iGlance/` and upload it here.

**Comment by D0miH** [comment]
Hey @nbigaouette,

thanks for providing this feedback. As your issue is related to #125 I will close this issue here as duplicate. If you want to post your log file please do so in #125.

Cheers👋🏼
