### ISSUE TITLE
iGlance ticks boxes that are disabled

### ISSUE THREAD

**Issue by GingkathFox** [iglance/iGlance#149]
**Describe the bug🐛**
I have the network usage widget disabled, but in the settings, the box is ticked.

**To Reproduce**

1. Disable a widget
2. click on another widgets settings
3. click back

**Expected behavior**

**Screenshots (Optional)**
![Screen Shot 2020-04-20 at 12 42 31 PM](https://user-images.githubusercontent.com/33764485/79776885-683a9900-8304-11ea-9715-4d9b71eb09b9.png)

**Desktop (please complete the following information):**

- MacOS Version: 10.14
- Version of the app: 2.0.4

**Log**
Can't save the logfile, option is grayed out

**Comment by D0miH** [comment]
Hey @GingkathFox,
thanks for your bug report. This bug is related to #136 and will be fixed with the next update.
