### ISSUE TITLE
iGlance just closes after 10 minutes

### ISSUE THREAD

**Issue by MattVanEy** [iglance/iGlance#153]
**Describe the bug🐛**
As the title says iGlance just closes itself after 10 minutes. It doesn’t freeze, it just disappears.

**To Reproduce**
1. Open iGlance
2. Wait 10 minutes
3. See the graphs disappear

**Desktop**
- MacOS Version: 10.15.4
- Version of the app: 2.0.6

**Log**
[iGlance_log_2020_04_21_15_39.log](https://github.com/iglance/iGlance/files/4510326/iGlance_log_2020_04_21_15_39.log)

**Comment by D0miH** [comment]
Thanks for the bug report. I will look into it as soon as possible and release a hot-fix since this a serious flaw in the app.
