### ISSUE TITLE
Graph for memory and cpu utilization

### ISSUE THREAD

**Issue by D0miH** [iglance/iGlance#16]
**Is your feature request related to a problem? Please describe.**
The development of memory and cpu utilization is not visible.

**Describe the solution you'd like**
One way to make the development of the utilization visible, is by providing an area graph over time.

**Additional context**
As an example this might look like the graph in iStats.

**Comment by edilsonborges** [comment]
Looking forward for this features, @D0miH. By the way, do you have twitter or other social network?

**Comment by edilsonborges** [comment]
Looking forward for this feature, @D0miH. By the way, do you have twitter or other social network?

**Comment by D0miH** [comment]
No, at the moment I/we aren't on any social media. But if we are going to, I'll announce it here so you guys can be up-to-date. :)
