### ISSUE TITLE
Random crashes after mac sleeps

### ISSUE THREAD

**Issue by ChillarAnand** [iglance/iGlance#160]
**Describe the bug🐛**

When mac goes to sleep for some time and starts again, iGlance is crashing.

**To Reproduce**

This is happening erratically. 

**Desktop (please complete the following information):**

- MacOS Version:  10.14.6
- Version of the app: 2.0.7

**Log**

Advanced logging was disabled when the crash happened. Will attach logs when next crash happens.

**Comment by D0miH** [comment]
Thanks for reporting. I might have an idea what caused this. Will look into this asap.

**Comment by D0miH** [comment]
just to make sure, could you provide the crash report? You should find the crash report using the `Console.app` app or under `~/Library/Logs/DiagnosticReports`.

**Comment by ChillarAnand** [comment]
Attached all 10 crashes. The last crash is related to this bug. 

[ig.zip](https://github.com/iglance/iGlance/files/4530494/ig.zip)

**Comment by ChillarAnand** [comment]
Attached all 10 crashes. The last crash is related to this bug.

[ig.zip](https://github.com/iglance/iGlance/files/4530506/ig.zip)

**Comment by D0miH** [comment]
thanks👍🏼

should (hopefully) be fixed with the next update

**Comment by ChillarAnand** [comment]
Also, network speed sticks to 0 kbps at times.

I started a download and the speed is stuck at 0kbps forever but other tools are able to capture network speed. 

<img width="381" alt="ig" src="https://user-images.githubusercontent.com/4463796/80273026-70bc1680-86ec-11ea-95f7-521f1604f566.png">

**Comment by D0miH** [comment]
> Also, network speed sticks to 0 kbps at times.
Yeah this is a known issue and is related to #139
