### ISSUE TITLE
no autoupdate 2.0.6->2.0.7?

### ISSUE THREAD

**Issue by revonoc** [iglance/iGlance#161]
**Describe the bug🐛**
I haven't been getting any update prompts or autoupdates to your hotfix! Happy to manual update but thought you should know since I assume a lot of people are still on 2.0.6 if this is widespread

**To Reproduce**
doesn't update, I open window, no prompts, etc

**Expected behavior**
autoupdate

**Screenshots (Optional)**

**Desktop (please complete the following information):**

- MacOS Version: newest
- Version of the app: 2.0.6

**Log**
assume this isn't needed?

**Comment by D0miH** [comment]
Thanks for reporting it. Since I update my app manually to check if it is working after releasing a new version I didn't knew this.
I will check this out and see where the problem is.
