### ISSUE TITLE
iGlance 2.0.8 crashes when clicking Disk menu option

### ISSUE THREAD

**Issue by Planktonette** [iglance/iGlance#172]
**Describe the bug🐛**
After allowing iglance to update, the settings reverted to default. Entering iglance and then clicking on the disk menu option on the left causes an instant app crash.

**To Reproduce**

1. Go to show window
2. Click on disk

**Expected behavior**
App doesn't crash

**Desktop (please complete the following information):**

- MacOS Version: 10.15.4 (19E266)
- Version of the app: 2.0.8

**Log**
[iglangeproblem.txt](https://github.com/iglance/iGlance/files/4547782/iglangeproblem.txt)
[io.github.iglance.iGlance 2020-04-27--23-53-12-064.log](https://github.com/iglance/iGlance/files/4547783/io.github.iglance.iGlance.2020-04-27--23-53-12-064.log)

**Comment by D0miH** [comment]
Hey @Planktonette,
thanks for reporting the issue. I was aware of the crash right after publishing the update and uploaded a fixed app bundle for version 2.0.8 a few minutes afterwards. 
Please re-download the newest version of the app and check if the crash still occurs.

Sorry for the inconvenience!
