### ISSUE TITLE
iGlance never actually updates. Always shows the same data

### ISSUE THREAD

**Issue by ColtonIdle** [iglance/iGlance#173]
**Describe the bug🐛**
I recently installed iGlance and found it weird that after a few days my amount of memory shown stays the same. I looked at activity monitor and it's showing completely different results.

**To Reproduce**
None. Just using it as expected

**Expected behavior**
Updates

**Desktop (please complete the following information):**

- MacOS Version: 10.14.6 (18G4032)
- Version of the app: 2.0.5

**Log**
NA

**Comment by ColtonIdle** [comment]
Just noticed that there were 3 updates in the past few days. Updating now and will try again.

**Comment by D0miH** [comment]
Hey @ColtonIdle,

nevertheless, thanks for reaching out to us and reporting issues :)
