### ISSUE TITLE
The Show disk space usage tick reappears by itself

### ISSUE THREAD

**Issue by bailarin2020** [iglance/iGlance#192]
**Describe the bug🐛**
When you **Untick**  [DISK: Show disk space usage] this action is done alright and the graphic disappears as wished. However, the 'tick' gets back without user intervention (however the monitor is not actually showed, unless you untick & tick it yourself).

**To Reproduce**

1. Go to 'DISK: Show disk space usage'
2. Untick the box
3. Pick any other monitor (CPU, Battery,...)
4. Go back to Disk
5. The box has the tick on, again.

**Expected behavior**
It should remain unticked

**Screenshots (Optional)**

**Desktop (please complete the following information):**

- MacOS Version: 10.14.6
- Version of the app: 2.0.8

**Log**
[io.github.iglance.iGlance 2020-06-20--17-05-58-652.log](https://github.com/iglance/iGlance/files/4808257/io.github.iglance.iGlance.2020-06-20--17-05-58-652.log)

**Comment by D0miH** [comment]
Hey @bailarin2020,
thanks for reporting the issue. There is already an issue on this matter which was accidentally closed (#175). A fix is going to be published with the next update.
