### ISSUE TITLE
Right pane changes background color

### ISSUE THREAD

**Issue by bailarin2020** [iglance/iGlance#193]
**Describe the bug🐛**
At the very start, the right pane's background is dark night, but it changes to light gray some time later

**To Reproduce**
I cannot find a way to reproduce it... it just happen and keep that way even if I restart the app

**Expected behavior**
It should stay dark night...won't it?

**Screenshots (Optional)**
<img width="797" alt="Screen Shot 2020-06-20 at 12 43 51 PM" src="https://user-images.githubusercontent.com/67200466/85208292-afd5a500-b2f4-11ea-9121-7bef1b2c8413.png">

**Desktop (please complete the following information):**

- MacOS Version: 10.14.6
- Version of the app: 2.0.8

**Log**
<img width="797" alt="Screen Shot 2020-06-20 at 12 43 51 PM" src="https://user-images.githubusercontent.com/67200466/85208309-d398eb00-b2f4-11ea-9a75-0eba143b2547.png">

**Comment by D0miH** [comment]
Hey @bailarin2020,
since the right pane is translucent it changes the color depending on what is placed behind the iGlance window. Does this explain the shift in colors?

**Comment by bailarin2020** [comment]
Hi D0miH,
Yes, it does!

I just wonder...is that behavior in line with the statement "App adjusts to light & dark mode"
My Mac is set to Dark Mode and the rest of app stay dark no matter what you have in the back.
Anyway, this issue is set and closed (I guess)

Thanks for your effort, and for giving this fabulous app to the world !

**Comment by D0miH** [comment]
The statement "App adjusts to light & dark mode" means that if you use osx dark mode you get this color scheme:
<img width="400" alt="Screenshot 2020-06-21 at 17 40 14" src="https://user-images.githubusercontent.com/36657497/85228843-45049680-b3e6-11ea-9891-99b782c174e0.png">

When you use osx light mode on the other hand you get this color scheme:
<img width="400" alt="Screenshot 2020-06-21 at 17 41 18" src="https://user-images.githubusercontent.com/36657497/85228867-6bc2cd00-b3e6-11ea-851d-a53f24d8769a.png">
