### ISSUE TITLE
Future iGlance landing page

### ISSUE THREAD

**Issue by edwardbattistini** [iglance/iGlance#212]
What do you guys think about making one? 
I'm thinking single page application with a netlify pipeline to publish to GitHub?
I can do all of that if you guys want?

**Comment by D0miH** [comment]
Wow, you are amazing! I really appreciate your enthusiasm to help us with the project!
That would be very cool. The idea was that we will use GitHub Pages to host the site. But if I see correctly netlify is also free for individuals. In my opinion the website should be also open source here on GitHub such that we have all at one place. 
This is the repo for the github pages site (this is also where the release notes for the update popups are hosted): https://github.com/iglance/iglance.github.io
If you want you can fork this repo and start working. Let me know if you need any help :)

**Comment by edwardbattistini** [comment]
Awesome will fork and start to play

**Comment by D0miH** [comment]
Do you know what tech stack you will use?

**Comment by edwardbattistini** [comment]
oops... did not see that. So I've recycle a Jekyll project and cleaned it all up. 
The release notes is now a markdown file. 

https://github.com/edwardbattistini/iglance.github.io

Let me know if you are ok with that. otherwise I have a quick plain html with Bulma 0.9 on it

**Comment by edwardbattistini** [comment]
Here is a preview branch https://sad-ride-62f38a.netlify.app

**Comment by D0miH** [comment]
> Here is a preview branch https://sad-ride-62f38a.netlify.app

Looks great so far!👍🏼 

> So I've recycle a Jekyll project and cleaned it all up.
Thats great. I think a static site generate is simple and good to maintain the website without too much of a hassle.

**Comment by Moneypulation** [comment]
I've been working on the github page a bit. Currently on a test repository since it's still under development.

Repo: https://github.com/Moneypulation/iglance-test
Page: https://moneypulation.github.io/iglance-test/

Feedback or suggestions (what to add, remove, change etc.) would be cool

**Comment by D0miH** [comment]
Oh wow this looks amazing! 
Maybe we can use the updated screenshots. But everything else is just so nice!

**Comment by D0miH** [comment]
I just got another idea. Maybe we can add a "Fork me on GitHub"-badge to the right upper corner. Maybe something like [this](https://github.com/tholman/github-corners).

**Comment by D0miH** [comment]
@Moneypulation I updated the images using the implemented design. You can find the updated images [here](https://github.com/iglance/iGlance/issues/226#issuecomment-705691734). The images have a high resolution. If you need a lower resolution version just let me know :)

**Comment by Moneypulation** [comment]
Thx for the feedback! I updated the images and added the github corner feature. Right now, it's causing some problems in the mobile view. Need to have a look into that later when I have more time. But it probably just needs to be put in some bootstrap container. 

Should I push the website to the iglance website repository, or  wait for that until the website is finished?

**Comment by D0miH** [comment]
Sure, you can push it to the iglance website repo. But please keep the `release-notes.html` file since this file serves the release notes for Sparkle update pop-up.

**Comment by D0miH** [comment]
Very nice! 
Since the website is live now I am closing this issue.
