### ISSUE TITLE
iGlance uses a massive chunk of ram

### ISSUE THREAD

**Issue by GingkathFox** [iglance/iGlance#213]
**Describe the bug🐛**
iGlance uses a massive chunk of ram, it seems to increase based on the uptime

![Screen Shot 2020-07-27 at 10 52 32 AM](https://user-images.githubusercontent.com/33764485/88556824-72e98600-cff7-11ea-842c-6f5068a3f639.png)

**To Reproduce**

1. open iGlance
2. dont shut down your mac for a while (maybe a week)
3. view usage in Activity Monitor

**Expected behavior**
RAM usage stays low.

**Screenshots (Optional)**

**Desktop (please complete the following information):**

- MacOS Version: [e.g. 10.14.6]
- Version of the app: [e.g. 2.0.4]

**Log**
Please activate `Advanced Logging` in the settings, restart the app and perform the steps to reproduce the bug.
After the bug occurred, please open the iGlance window and in the app menu at the top left of the menu bar click on `Diagnostics > Save Logfile...`.

save logfile option is grayed out.

**Comment by D0miH** [comment]
Hey @GingkathFox,
I think you are still on an old version of the app since this issue was already reported in #177. 
Please try to manually update by opening the iGlance window and clicking on `iGlance > Check for Updates` in the menu bar.

**Comment by GingkathFox** [comment]
aw dammit homebrew, youre supposed to update for me D:

will close now, if it happens again ill reopen
