### ISSUE TITLE
Network speed not having enough space when > 10.00 MB/s

### ISSUE THREAD

**Issue by hesyifei** [iglance/iGlance#214]
**Describe the bug🐛**
When the network speed is faster than 10.00 MB/s, the number touches the upload/download symbols on the left.

**To Reproduce**

1. When the network speed is greater than 10.00 MB/s, the number touches the symbol sometimes.

<img width="76" alt="bad 1: 38.45 MB/s" src="https://user-images.githubusercontent.com/4939421/88863806-45d6e680-d236-11ea-8324-2450d951c4ed.png">
<img width="78" alt="bad 2: 40.58 MB/s" src="https://user-images.githubusercontent.com/4939421/88863782-39528e00-d236-11ea-827f-3a91a9538f14.png">

2. It also seems that since the font for the number is not monospaced, some numbers takes longer space than the other (e.g., "40.58" takes longer space than "37.11"). So it fits sometimes:

<img width="75" alt="good: 37.11 MB/s" src="https://user-images.githubusercontent.com/4939421/88863783-3b1c5180-d236-11ea-9483-8944b7c24db7.png">

**Expected behavior**
I can think of a few alternatives:
1. The symbols on the left will adjust automatically based on the width of the number. Or move the symbols to the right.
2. Adjust the font size of the network speed automatically to fit the set width.
3. Use monospaced font for the number as well as the "MB/s" and "KB/s" (but still also need option (1) or (2) if the speed is e.g., > 100.00 MB/s).

**Desktop (please complete the following information):**

- MacOS Version: 10.15.6
- Version of the app: 2.0.9

**Log**
N/A

**Comment by D0miH** [comment]
Hey @hesyifei,
thanks for your bug report. As you already mentioned I think this bug should be solved by changing two things:
1. use monospaced font for the numbers as well as the units
2. to save space in the menu bar the network speed item has a minimum width. If the current calculated width of the text is wider than that minimum width, the network item should be made wider. This way the network speed menu bar item gets only wider when it is necessary and no space is wasted.
