### ISSUE TITLE
Unable to autostart on boot

### ISSUE THREAD

**Issue by maesa** [iglance/iGlance#22]
MBP 2014, 15", MacOS Mojave 10.14.3

iGlance 1.3.1

1. Remove manually installed iGlance (1.3.0)
2. Run "brew cask instal iGlance"
3. Tick "Autostart on Boot"
4. See error "Something went wrong, sorry"

Please let me know if there's any additional information needed

**Comment by D0miH** [comment]
Hi @maesa,

thanks for reporting the bug. 
We are aware of the issue and this should be fixed (with [this](https://github.com/iglance/iGlance/commit/395f8d06a0a66e6f6c2b0b307fd4717eb2edb7b4) commit) in the next update.
