### ISSUE TITLE
Update screenshots in Readme

### ISSUE THREAD

**Issue by D0miH** [iglance/iGlance#226]
**Is your feature request related to a problem? Please describe.**
Screenshot of the app in the readme are displaying the old design.

**Comment by edwardbattistini** [comment]
@D0miH do you have a screen grab of the new UI? I'm not too sure how to build it on my Mac

**Comment by edwardbattistini** [comment]
I could not clone the repo for some reason... so I was not able to update the readme...
Anyway here are some new assets
[Detailed system info.pdf](https://github.com/iglance/iGlance/files/5333713/Detailed.system.info.pdf)
![Detailed system info](https://user-images.githubusercontent.com/6288298/95201300-a4d94e80-07d7-11eb-950f-0c11bc1ac2c3.png)
<img width="1024" alt="Detailed system info@2x" src="https://user-images.githubusercontent.com/6288298/95201303-a571e500-07d7-11eb-856f-38cb8c6a9f3f.png">
![Detailed system info@3x](https://user-images.githubusercontent.com/6288298/95201305-a60a7b80-07d7-11eb-845f-f91f5b476c25.png)
[Logo.pdf](https://github.com/iglance/iGlance/files/5333714/Logo.pdf)
![Logo](https://user-images.githubusercontent.com/6288298/95201310-a6a31200-07d7-11eb-95f1-7741a97a5b64.png)
![Logo@3x](https://user-images.githubusercontent.com/6288298/95201312-a6a31200-07d7-11eb-8a4d-d835429a53c4.png)
<img width="427" alt="Logo@x" src="https://user-images.githubusercontent.com/6288298/95201313-a73ba880-07d7-11eb-9de7-22a2caf4d44a.png">
<img width="1024" alt="FutureIglance" src="https://user-images.githubusercontent.com/6288298/95201424-d7834700-07d7-11eb-91a8-5588534f7f2c.png">
![iglance-featured](https://user-images.githubusercontent.com/6288298/95201433-d94d0a80-07d7-11eb-9f2e-23efb9486873.png)
<img width="1024" alt="iglance-featured1" src="https://user-images.githubusercontent.com/6288298/95201438-db16ce00-07d7-11eb-95a3-6516479321b3.png">

If you have the chance to send me a screen grab of the implemented interface (cmd + Shift + 4 + space + click the window )
I'll send you new ones 😄 

all the best

**Comment by D0miH** [comment]
This looks really nice! I really like the look of the logo. Matches the new design of the app perfectly 👍 
Here are the screenshots of the new ui:
<img width="942" alt="Screenshot 2020-10-06 at 14 31 42" src="https://user-images.githubusercontent.com/36657497/95201913-defb1e00-07e0-11eb-8e13-09415d07a166.png">
<img width="942" alt="Screenshot 2020-10-06 at 14 32 17" src="https://user-images.githubusercontent.com/36657497/95201918-e02c4b00-07e0-11eb-866c-a60e7b9b3822.png">

**Comment by D0miH** [comment]
I think that in the next few updates I will add the function to arrange the menu bar items using drag and drop and prettify the dashboard.

May I ask you where you get the image of the macbook pro? I was looking for such an asset but did not find one.

**Comment by Moneypulation** [comment]
Looks really nice! Gonna make use of the images on the website I'm working on right now

**Comment by edwardbattistini** [comment]
here you go @D0miH https://facebook.design/devices

**Comment by edwardbattistini** [comment]
let me know @Moneypulation if you want any help 😉

**Comment by D0miH** [comment]
Thanks a lot! My idea was that maybe we could show the sketch of the device on the new dashboard in addition to the system information.

**Comment by edwardbattistini** [comment]
<img width="698" alt="Screenshot 2020-10-06 at 14 06 38" src="https://user-images.githubusercontent.com/6288298/95205353-28e20500-07dd-11eb-8770-95141bdb06c7.png">

Do you mean like in the MacOS info?

**Comment by D0miH** [comment]
Exactly! Maybe we could even add different desktop backgrounds depending on the current MacOS version.

**Comment by Moneypulation** [comment]
> let me know @Moneypulation if you want any help 😉

Will definitely do :) Appreciate the help!

**Comment by edwardbattistini** [comment]
> Exactly! Maybe we could even add different desktop backgrounds depending on the current MacOS version.

Nice details!

**Comment by D0miH** [comment]
I updated the app window in the images:
<img width="1004" alt="app_window_logo_combined" src="https://user-images.githubusercontent.com/36657497/95488661-1b23af80-0996-11eb-8ca4-d4c765f45285.png">
<img width="1904" alt="product_image" src="https://user-images.githubusercontent.com/36657497/95488666-1c54dc80-0996-11eb-806f-8fc61ebb8c81.png">

**Comment by D0miH** [comment]
> here you go @D0miH https://facebook.design/devices

@edwardbattistini I haven't found any license. Do you know if we can just use them in our app? I mean we would credit them anyway but they don't mention if we can use them e.g. on a web page.
