### ISSUE TITLE
Contribution guide lacks information on building/running

### ISSUE THREAD

**Issue by Anders-E** [iglance/iGlance#237]
I was looking at doing some contributions to this project as I like it a lot so far.

However, there are no instruction on how to build/run the project in the Contribution Guide and I find myself a bit confused. I apologize if this is stuff I "should know" but I'm very, very new to the whole Apple dev ecosystem so it would be nice with some building/running guidelines.

Thank you for a great project!

**Comment by D0miH** [comment]
Hey @Anders-E,
glad to hear that you want to contribute. This is nothing you „should know“ and I am glad that you are reaching out for help👍🏼
I can see that mac developing lacks a bit of documentation on the web. 
I will summarize all necessary information to get started and will update the contribution guide.
I will update you here here when the contribution guide is up go date. :)

**Comment by D0miH** [comment]
So I added an additional paragraph to the contribution guide for setting up the project using Xcode. Hope this helps.
Since my project is already set up locally, it is difficult to figure out what might be missing 
What additional info would be helpful for you to get started?

**Comment by Anders-E** [comment]
Got it up and running! Was just a bit confused as to what directory/file I was supposed to load into XCode (as well as the per project signing options in XCode).

Thank you very much!

**Comment by D0miH** [comment]
Ahh! Good point with the signing options. I will add that as well that the signing team has to be changed for each sub-project.

**Comment by Anders-E** [comment]
Yes, I think that would be helpful to newcomers to the Apple dev ecosystem like myself.

Once again thank you very much!

**Comment by D0miH** [comment]
Sure, no problem :)
If you get stuck on understanding the code or need any help, feel free to reach out 😁

**Comment by Anders-E** [comment]
Thank you, much appreciated!
