### ISSUE TITLE
Bug when toggling "autostart on boot"

### ISSUE THREAD

**Issue by edilsonborges** [iglance/iGlance#24]
Autostart on Boot is not working. An error is given:

**Version**
1.3.1

**Screenshot**
![image](https://user-images.githubusercontent.com/3504039/53539558-cbf67700-3af0-11e9-8526-197a83e5579e.png)

**Gear**
Mbp 15" Mid 2015
macOS Mojave 10.14.2

**Comment by D0miH** [comment]
Hey @edilsonborges,
yeah we are aware of this bug. I think I will release an update with a hot fix today. :)

**Comment by edilsonborges** [comment]
Thanks!
