### ISSUE TITLE
GUI redesign

### ISSUE THREAD

**Issue by D0miH** [iglance/iGlance#25]
**Is your feature request related to a problem? Please describe.**
The user interface looks a bit crammed. Is related to #23.

**Describe the solution you'd like**
The solution would be to redesign the user interface.

**Comment by D0miH** [comment]
@Moneypulation Here is the new version of the prototype. First one is the main view of the app. The second picture is the view of the settings menu which can be opened by clicking on the little cogwheel at the left bottom.

![mainapp 2x](https://user-images.githubusercontent.com/36657497/53818937-3f710c00-3f69-11e9-9739-0fcf2d865f98.png)
![settings 2x](https://user-images.githubusercontent.com/36657497/53818949-45ff8380-3f69-11e9-8db1-027aa191641b.png)

**Comment by Moneypulation** [comment]
looks good, maybe we should highlight the cogwheel a bit more. it's a bit too hidden imo

**Comment by D0miH** [comment]
Yeah, good point. I guess giving it the same color as the font does the trick.

**Comment by wx-Yao** [comment]
Oh please, it'd be good if we can find our public IP in the network section somewhere. Normally we
're behind NAT but we (at lease me..?) have the need to know the router's public IP sometimes. Tell me if I need to open another issue for the feature request.

Yeah I understand other ways to find the IP are possible but if this tool has it, why bother?:)
