### ISSUE TITLE
Installation is failed using latest Homebrew

### ISSUE THREAD

**Issue by kawarimidoll** [iglance/iGlance#252]
**Describe the bug🐛**
Installation is failed using latest Homebrew. This is not bug of iGlance, but need to fix installation instructions in README.md.

**To Reproduce**
Run `brew cask install iglance` in the terminal.

**Screenshots**
![スクリーンショット 2020-12-25 10 45 32](https://user-images.githubusercontent.com/8146876/103113489-56cd3c00-469e-11eb-9be9-c22e281c1b6a.png)

**Desktop (please complete the following information):**

- MacOS Version: 10.15
- Homebrew Version: 2.7.0

**Comment by naveenyadav15** [comment]
I also faced the same error. I solved it using this command.
`brew install iGlance`

**Comment by AT181903** [comment]
There is a problem in readme file, the correct command is brew install --cask iglance

**Comment by jesseclm** [comment]
I have create a PR to fix this issue
