### ISSUE TITLE
crashes on macOS 10.14.5

### ISSUE THREAD

**Issue by thanosa75** [iglance/iGlance#26]
**Describe the bug**
crashes randomly in macOS 10.14.5, mbp 2015

**To Reproduce**
1. Crashes while working

**Expected behavior**
should work

**Screenshots**
No screenshot available, see crash report attached here
[iGlance_2019-06-28-180058_tangelatos-mbp.crash.zip](https://github.com/iglance/iGlance/files/3339823/iGlance_2019-06-28-180058_tangelatos-mbp.crash.zip)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser N/A
 - Version 1.3.2

**Comment by thanosa75** [comment]
Additional crash report files available on request.

**Comment by D0miH** [comment]
Hey @thanosa75,

thanks for the bug report. I look into this.

**Comment by D0miH** [comment]
So I looked into this and it should be fixed with the next release.
