### ISSUE TITLE
Incorrect battery health

### ISSUE THREAD

**Issue by h3n4l** [iglance/iGlance#264]
**Describe the bug🐛**
Incorrect battery health on dashboard.

**To Reproduce**

1. Go to "iGlance"
2. Click on "Dashboard"
3. See wrong battery health

**Screenshots (Optional)**
Battery Health on apple settings:
<img width="314" alt="图片" src="https://user-images.githubusercontent.com/87714218/151585129-3c841539-532e-4ea8-b399-dd34984ffaf7.png">
Wrong battery health on dashboard:
<img width="830" alt="图片" src="https://user-images.githubusercontent.com/87714218/151585280-802884ed-b3bc-457f-80a4-ccb3a0aebb64.png">

**Desktop (please complete the following information):**

- MacOS Version: 12.1
- Version of the app: 2.1
- M1 silicon macbook pro 13'

**Log**
[io.github.iglance.iGlance 2022-01-28--16-25-48-897.log](https://github.com/iglance/iGlance/files/7960281/io.github.iglance.iGlance.2022-01-28--16-25-48-897.log)

**Comment by kennedy26** [comment]
Reset SMC and recalibrate battery (drain to completely off, after 6-8 hours plug in charger to 100%)

**Comment by h3n4l** [comment]
> 

I will try it.

**Comment by h3n4l** [comment]
> Reset SMC and recalibrate battery (drain to completely off, after 6-8 hours plug in charger to 100%)

I will try it.
