### ISSUE TITLE
iGlance still shows version 1.3.2 

### ISSUE THREAD

**Issue by suschizu** [iglance/iGlance#28]
hey @D0miH - I think you forgot to update the bundle version in the Info.plist - it still shows 1.3.2 instead of 1.3.3 as latest version 
<img width="441" alt="Screenshot 2019-07-22 at 19 19 09" src="https://user-images.githubusercontent.com/16004333/61651407-1d78eb80-acb6-11e9-912a-26788c3f57d3.png">

**Comment by D0miH** [comment]
Hi @suschizu,
thanks for pointing it out.
Should be fixed with 1.3.4.

**Comment by suschizu** [comment]
thanks :)
