### ISSUE TITLE
Network speed shown in wrong order

### ISSUE THREAD

**Issue by wx-Yao** [iglance/iGlance#29]
**Describe the bug**
Normally for the network speed monitoring, the line above means "upload speed" and the line below means "download speed", which is intuitive. But on my macOS 10.14.5 in the newest version, the order is reversed. i.e., the line above means "download speed".

**To Reproduce**
Steps to reproduce the behavior: Just tick the network monitor toggle.

**Expected behavior**
Reversed displaying order of the two speeds.

**Screenshots**
![image](https://user-images.githubusercontent.com/20643897/61719419-3661c980-ada8-11e9-89bd-f87873e8968e.png)

The screenshot is taken when I'm **downloading** something, you can see that the download speed is on the upper line. I'm not sure if it is intentionally designed to be like this.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Version of the app: 1.3.3

**Additional context**
N/A

**Comment by D0miH** [comment]
Hi @wx-Yao,
thanks for the suggestion. In fact we didn't think about this very much and your point is absolutely valid. 

The labels will be switched in the update i will release today:)

**Comment by wx-Yao** [comment]
:) Cheers mate

**Comment by Moneypulation** [comment]
I think instead of changing the order for everyone, we can add an option in the network settings tab to switch the order of down- and upload. This way, people can choose whichever order fits them best. Anything against that?

**Comment by wx-Yao** [comment]
lol Em I don't mind. But I just think that ... will anyone feel comfortable if he finds the "download" speed is on the "upper line"? I mean, yeah of course options are always good. I just don't really think someone would use it IMHO because intuitively, up is up, down is down :p.

But thanks for the interesting suggestion. I don't mind if you add it.

**Comment by Moneypulation** [comment]
It was actually intuitive for me that the download speed was at the top. I think everyone has their own preferences which is why we want to keep everything customizable.
But I see your point. I guess we'll switch the upload speed to position it at the top as the default value since it makes more sense. I'll add the feature for the next version then

**Comment by wx-Yao** [comment]
Yeah exactly. Everyone has different intuitions.
Just make it an option and it'll be good. Thanks mate.
