### ISSUE TITLE
CPU temp inaccurate

### ISSUE THREAD

**Issue by mjstelly** [iglance/iGlance#33]
**Describe the bug**
iGlance cpu temp is way off. It reports my cpu at 129°. Same temp on SystemX is 98°.

**To Reproduce**
1. Launch both SystemX and iGlance
2. Enable CPU temp reporting using equal scales (F or C)

**Expected behavior**
Both scales should be reporting equal values

**Screenshots**
iGlance on the left / SystemX on the right
<img width="251" alt="Screen Shot 2019-08-02 at 8 17 38 AM" src="https://user-images.githubusercontent.com/313819/62373172-d8975500-b4fe-11e9-8568-a8c58af95b5a.png">

**Desktop (please complete the following information):**
 - OS: MacOS X 10.14.5
 - Version of the app: iGlance 1.3.5, SystemX ?

**Comment by Moneypulation** [comment]
Hey @mjstelly 

can you answer us the following questions to help us track down the problem:

1. What machine are you using (e.g. MacBook Pro 2015,2016, Hackintosh, ...) ?
2. Which of the two temp values (iGlance, SystemX) is the correct one? 
3. Is the temp from iGlance always off by the same constant value? For instance, by the value 33*F based on your screenshot
4. and finally is the problem consistent on your machine, so that it will never show the "real" temp value?

**Comment by mjstelly** [comment]
1. System: MacBook Pro (15-inch, 2018)
2. Since I don't have a third temp gauge to confirm, I can only guess that
it's the lower SystemX value.
3. I removed SystemX shortly after this since neither app is reliable. So I
can't say for sure. Guess I forgot to remove iGlance. It's reading 156°
right now which would probably be causing a system meltdown if it were
correct.
4. Yes.

Sincerely,
Michael Stelly | M: +1.918.978.2000 | LinkedIn
<http://www.linkedin.com/in/mstelly> | Twitter
<https://twitter.com/michaelstelly>

**Comment by D0miH** [comment]
Hi @mjstelly,

i have a MacBook Pro 15" 2018 too and can't reproduce the bug on my machine. 
Is it possible, that you chose to display Fahrenheit instead of Celcius? You can check this setting in the settings menu of the cpu. 

Concerning SystemX i wanted to say that this app is not sold by us. A third party took our code and sells it in the app store (which is totally correct concerning legal terms). However we don't know whether he made any changes to the code and therefore can't help you if your problem concerns the SystemX app.

Cheers

**Comment by mjstelly** [comment]
Ahh. I didn’t know about the business model. That’s interesting since it provides an upgrade link which redirects to your git repo. 🤨

At any rate, the F or C conversion scale is irrelevant. The base value is incorrect. I’ll see if I can find some  other tool to provide a comparison. But , as a developer myself, I know the burden to debug and provide a fix is on the product owner.

Sincerely,
Michael Stelly | M: +1.918.978.2000 Blog | LinkedIn | Github

**Comment by D0miH** [comment]
yeah, you could download the trail of [iStats](https://bjango.com/mac/istatmenus/). This will give you hopefully the correct correct temperature value.

> Ahh. I didn’t know about the business model. That’s interesting since it provides an upgrade link which redirects to your git repo. 🤨

So you are saying that the app is for purchase in the app store and once there is an update you delete SystemX and instead install iGlance from our repo?

**Comment by mjstelly** [comment]
Once SystemX launches, you receive this modal which points to your repo.
[image: Screen Shot 2019-08-07 at 10.14.27 AM.png]

Sincerely,
Michael Stelly | M: +1.918.978.2000 Blog <https://medium.com/@michaelstelly>
| LinkedIn <http://linkedin.com/in/mstelly> | Github
<https://github.com/mjstelly>
On Aug 7, 2019, 10:10 AM -0500, Dominik H. <notifications@github.com>,
wrote:

yeah, you could download the trail of iStats
<https://bjango.com/mac/istatmenus/>. This will give you hopefully the
correct correct temperature value.

Ahh. I didn’t know about the business model. That’s interesting since it
provides an upgrade link which redirects to your git repo. 🤨

So you are saying that the app is for purchase in the app store and once
there is an update you delete SystemX and instead install iGlance from our
repo?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iglance/iGlance/issues/33?email_source=notifications&email_token=AACMTWZZ3UBSUERH7X6UOR3QDLQXDA5CNFSM4II5VPE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3YXJTI#issuecomment-519140557>,
or mute the thread

**Comment by tom10271** [comment]
i have the same issue too, in SystemX it is just 3x-4x degree celsius but 70+ for iGlance

**Comment by wimbos2208** [comment]
Hi there,

Same issue (temperature way off), showing -86 degrees C (it is definitely not that cold here :-))
Imac Retina 5k 27" late 2014 model
Running Mojave 10.14.6

**Comment by tom10271** [comment]
My MBP hits 100 degrees C all the time

**Comment by D0miH** [comment]
I changed the sensor which is used for reading the temperature now from the cpu die sensor to the cpu proximity sensor.

Now the correct (same as in iStats) should be displayed.
