### ISSUE TITLE
updated app won't launch

### ISSUE THREAD

**Issue by mjstelly** [iglance/iGlance#34]
**Describe the bug**
App fails to launch on latest update. Tried installing using both brew and the dmg. Same result.

**To Reproduce**
1. Download dmg or install through `brew`
2. Click on iGlance icon

**Expected behavior**
App should appear in status bar

**Actual behavior**
Finder window flashes briefly, then nothing else.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Version of the app: 1.3.6

**Comment by ttsymlov** [comment]
Same os and app version - works fine for me

**Comment by D0miH** [comment]
Hi @mjstelly,

this is very strange. Could you provide a crash report?
You can find crash reports in `~/Library/Logs/DiagnosticReports/`.

**Comment by mjstelly** [comment]
Sincerely,
Michael Stelly | M: +1.918.978.2000 | LinkedIn
<http://www.linkedin.com/in/mstelly> | Twitter
<https://twitter.com/michaelstelly>
