### ISSUE TITLE
iGlance freeze

### ISSUE THREAD

**Issue by RobertasMurnikovas** [iglance/iGlance#35]
After some time of my mac inactivity or being put to sleep I've noticed some strange behaviour, the app is not starting, it looks like it's running, but none of the info is showing anything even though I'm downloading something or my CPU is running on max, it just seems to freeze.

MacOS 10.14.6
iGlance 1.3.6

**Comment by D0miH** [comment]
hmm🤔 . I have no idea what could cause this. 
Did you observe any pattern when this happens? Is this consistently happening when you are waking your mac up or is this happening rather random?

**Comment by RobertasMurnikovas** [comment]
This is happening kinda random, it doesn't happen often, just from time to time and can see that iGlance freezed and I just quit it and re-open again, haven't noticed this freeze in a while now, but maybe I just didn't gave it any attention.

**Comment by D0miH** [comment]
> haven't noticed this freeze in a while now
Ok. Maybe this issue was fixed with the new version. I will close this issue and if you notice that iGlance freezes again feel free to reopen the issue.
