### ISSUE TITLE
Notarize the app by Apple

### ISSUE THREAD

**Issue by D0miH** [iglance/iGlance#37]
**Describe the bug**
Since macOS Catalina all apps must be notarized by Apple. Therefore the app currently can't be launched under macOS Catalina.

**To Reproduce**
Simply try to launch the app

**Expected behavior**
The app launch as expected.

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Version of the app: 1.4

**Comment by rwojnarowski** [comment]
App is working fine under macos catalina. Just go into security settings and open app from unknown source

**Comment by D0miH** [comment]
Oh yeah you are right. Skimming through the notarizing info-page of apple I thought maybe we can notarize the app without signing it with a developer account. Since thats not possible we can close this issue.
