### ISSUE TITLE
Add disable update check option

### ISSUE THREAD

**Issue by tom10271** [iglance/iGlance#45]
Maybe it is good to keep upgrading but I found update releases are too frequent and I don't care about the update that I cannot find anything improved.

**Comment by Moneypulation** [comment]
Hey @tom10271.

thanks for your feedback. I'm completely with you regarding this point. I'll create an option to turn out update notifications in the next days

**Comment by D0miH** [comment]
I am sorry I accidentally closed this issue

**Comment by tom10271** [comment]
"Check for updates on wake up" can now be disabled

This is not working. I have unchecked it and still got 1.4.3 update popup

**Comment by D0miH** [comment]
oh you are right. I spotted a bug in the code.
This will be fixed with the next update.

**Comment by tom10271** [comment]
When will this be released?

**Comment by D0miH** [comment]
Hey,

the fix should already be released with the last currently available version of the app. 
Do you experience any specific problem?

PS: Sorry I didn't let you know that the bug is now fixed 🙈

**Comment by tom10271** [comment]
Oh I thought this is not included in 1.4.3 as it is not mentioned in releast note.

**Comment by D0miH** [comment]
oh, yeah I forgot to put in the release notes
