### ISSUE TITLE
A note to the devs...

### ISSUE THREAD

**Issue by tempusthales** [iglance/iGlance#49]
I had bought an app on the Mac App Store called SystemX, which advertised as having a full screeen panel with a ton of graphs.  It didn't appear to have anything of the sorts.  I went online looking for more info where I came across another post that denounced that the app in the Mac App Store was stolen.  I then found the iGlance website on Github.  This made me very upset, so I filed a report with Apple and this is what I wrote to them: 

> The product listed on the Mac App Store under the name iStats X is a fraud - The dev lifted the code from iGlance, (https://github.com/iglance/iGlance/releases),  packaged it, and sells in on the Mac App Store. 
> 
> This is unethical, copyright infringement and illegal. Had I known this beforehand, of course, I wouldn't have bought this product from the Mac App Store, and instead downloaded it from the rightful owners in https://github.com/iglance/iGlance/releases. As always, caveat emptor - buyer beware. I am copying a response by the original developers of this app who were asked by someone else about SystemX and this is what they had to say about it: "Concerning SystemX I wanted to say that this app is not sold by us. A third party took our code and sells it in the app store (which is totally correct concerning legal terms)".
> 
> Furthermore I opened the contents of the application and I found a folder in `/Applications/iStats\ X.app/Contents/Library` that contains a folder called `/LoginItems` that has an app called _iGlanceLauncher.app_ (fullpath: `/Applications/iStats\ X.app/Contents/Library/LoginItems/iGlanceLauncher.app`) which you can find out more info here: [https://github.com/iglance/iGlance/tree/master/iGlance/iGlanceLauncher](https://github.com/iglance/iGlance/tree/master/iGlance/iGlanceLauncher) .  
> 
> So as you see this application being on the Mac App Store is a scam and as such I would like to request the developeron the Mac App Store to be banned from the MAS for stealing someone else's work.  Thanks!

I sincerely hope whatever wrong this has caused you and your app, is writed at some point. I apologize if this is not the place to leave this, but I couldnt find an email to send you this.

**Comment by D0miH** [comment]
Hey @tempusthales,

thanks for your positive support. I am sorry that you were scammed. 
I hope Apple will respond to your request and take this app down. 

It would be nice if you posted the answer of Apple here in this issue.

**Comment by D0miH** [comment]
As a follow-up for @tempusthales or others that read this thread I wanted to add that maybe you could try to refund the app.

More information can be found on this website:
https://support.apple.com/en-us/HT204084
