### ISSUE TITLE
Seperate on/off toggles for upper/lower battery notif

### ISSUE THREAD

**Issue by GingkathFox** [iglance/iGlance#50]
**Is your feature request related to a problem? Please describe.**
I love how i can get notifs if my battery drops under a certain percentage. What i don't like is the notif when my battery goes above a certain percentage. Kinda redundant since the charger has the red/green led that turns green when its fully charged.

**Describe the solution you'd like**
It would be nice to have separate checkboxes for upper and lower notifs. Currently my workaround is setting the upper limit to 21%.

**Comment by D0miH** [comment]
Hey @GingkathFox,

thanks for your feature request. This should be very simple to implement. 
I will start working on the open issues the next few days :)

**Comment by GingkathFox** [comment]
nice, thanks!
