### ISSUE TITLE
Percentage of battery in taskbar

### ISSUE THREAD

**Issue by GingkathFox** [iglance/iGlance#56]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to see the percentage remaining without having to click on the battery icon.
**Describe the solution you'd like**
I'd like to have a setting to see the percentage of the battery in the battery icon, and be able to switch from percentage to time remaining (maybe holding shift while clicking?).

**Comment by D0miH** [comment]
This seems like a good idea. Having this feature one could remove the default battery from the main menu.

Since I am currently rewriting the whole app I will look into this after #25 is merged.
