### ISSUE TITLE
Percentage under 10% is displayed as 0N%

### ISSUE THREAD

**Issue by GingkathFox** [iglance/iGlance#57]
**Describe the bug**
When the percentage drops under 10%, the percentage is displayed as 0N%.

**To Reproduce**
1. Drain battery.

**Expected behavior**
Percentage is displayed as N%

**Screenshots**
![Screen Shot 2019-12-11 at 11 34 48 AM](https://user-images.githubusercontent.com/33764485/70641149-25a4d980-1c0b-11ea-8065-d33c1dbdf260.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Version of the app: 1.4.1

**Additional context**

**Comment by D0miH** [comment]
Yeah, without the leading zero it is prettier. 

Will be fixed with the next update.
