### ISSUE TITLE
Both high and low battery notifs say "Low"

### ISSUE THREAD

**Issue by GingkathFox** [iglance/iGlance#65]
**Describe the bug**
Title. heres a screenie: 
![Screen Shot 2019-12-28 at 12 42 24 AM](https://user-images.githubusercontent.com/33764485/71539513-0dbb9e00-290b-11ea-9bb5-1498d5c3de82.png)

**To Reproduce**
1. Open settings and click "Battery"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mojave 10.14
 - Version of the app: 1.4.2

**Additional context**

**Comment by D0miH** [comment]
oh, you are right! 
Well, that happens when you use copy and paste🙈

Will be fixed in the next update:)
