### ISSUE TITLE
I dont know why but everytime I turn off Wi-Fi, iGlance just quit

### ISSUE THREAD

**Issue by leet-physics** [iglance/iGlance#70]
I have tried reinstall, but not work.

**Comment by D0miH** [comment]
Hey @leet-physics,

thanks for your bug report. 
I guess iGlance is somehow crashing when you turn off Wifi. Could you provide a crash report?

You can get the crash report by opening the Console.app application and click in the sidebar on "Crash Reports". iGlance should show up in the list of crash reports. Then right click on the iGlance crash report and click "show in finder" to upload the file here.

**Comment by TheTilodon** [comment]
I got the same problem when I go on VPN. BTW the VPN traffic will not be shown.

**Comment by D0miH** [comment]
Hi guys, 
so I could reproduce this bug and looked into the problem. This should be fixed with the next update:)
