### ISSUE TITLE
Internet usage per session

### ISSUE THREAD

**Issue by 4goodapp** [iglance/iGlance#74]
Is it possible to have internet/network bandwidth usage in mb in networks session?
It's handy when you use limited data.
Currently we only have network speed.

**Comment by D0miH** [comment]
Hey @4goodapp,
thanks for your suggestion. 
At the moment the internet bandwidth usage is shown for the last hour. If I understand you correctly your suggestion is to move that into the menu bar and instead of displaying the bandwidth usage of the last hour, display the bandwidth usage of the whole session, correct?

This is a good idea indeed. However one question I have is what the definition of a "Session" is. Should a session be the time from wakeup of the Mac until sleeping/locking. Or should the user be able to manually start/end the session with a button click?

**Comment by 4goodapp** [comment]
> internet bandwidth usage  is shown for the last hour.

Ohh, Thanks, I didn't expect we have this info by clicking on the networks speed. 
But you're right, I suggest to have an option to display it into the menu bar just like the the one for speed. (I personally don't monitor networks speed usually).

> display the bandwidth usage of the whole session, correct?

Exactly, but with option to reset it manually too.
the idea is to replace [Bandwidth+](https://apps.apple.com/us/app/bandwidth/id490461369?mt=12) which I've been using till now with this all-in-one solution.

> However one question I have is what the definition of a "Session" is.

This:
_"Or should the user be able to manually start/end the session with a button click?_

Let me know if you need more details please and thanks for this amazing app.

**Comment by D0miH** [comment]
This seems like a very good idea 👍 
I will look into this after releasing the next version :)

**Comment by 4goodapp** [comment]
Perfect!

_Offtopic:_

What are the main feature of the next version btw?

**Comment by D0miH** [comment]
At them moment I am rewriting the whole app. As a result the app should be more stable and has a new user interface. You can see some of the features [here](https://github.com/iglance/iGlance/projects/1).

**Comment by 4goodapp** [comment]
Awesome, you available on Discord?

**Comment by D0miH** [comment]
No, I don't have a Discord account/server.

**Comment by 4goodapp** [comment]
OK,
Well am interested to participate for the website if it's not done yet.
Have any idea about it

**Comment by D0miH** [comment]
This would be awesome. I created a seperate issue for this (#76). 
My current idea is to use github pages with a jekyll theme. However I haven't thought about what should be displayed on the website. I need to think about that. I will then update issue #76 and let you know :)

**Comment by 4goodapp** [comment]
OK, Perfect!

**Comment by D0miH** [comment]
Hey @4goodapp,

do you still want to work on the website?
I create a new issue for the website over at https://github.com/iglance/iglance.github.io/issues/1.
I added some things that should be mentioned on the website. If you want you can create some sort of sketch and post it as a comment to the issue.

**Comment by 4goodapp** [comment]
Hey, Of course, I'll take a look. Will send some sketch.

**Comment by 4goodapp** [comment]
[Group 15.pdf](https://github.com/iglance/iGlance/files/4398073/Group.15.pdf)
![Group 11](https://user-images.githubusercontent.com/6249230/77836430-fb414280-714d-11ea-95b2-63ba71f1e835.png)
![Group 12](https://user-images.githubusercontent.com/6249230/77836432-fed4c980-714d-11ea-8e7e-fa7cf898b2e9.png)
![Group 13](https://user-images.githubusercontent.com/6249230/77836433-0005f680-714e-11ea-8bc2-fea7ddde35ac.png)
![Group 15](https://user-images.githubusercontent.com/6249230/77836434-009e8d00-714e-11ea-9e2d-9770cb85fec1.png)
[Group 16.pdf](https://github.com/iglance/iGlance/files/4398074/Group.16.pdf)
![Group 16](https://user-images.githubusercontent.com/6249230/77836435-04321400-714e-11ea-85c0-1870f51033f0.png)


What do you think about these? 😬

**Comment by D0miH** [comment]
Hey, 
thanks for your sketches. They look awesome!

I would prefer the grey/blueish color theme as it it fits better to the light theme of the app. 
An additional color theme of the website for the dark theme of the app would be nice. We could then maybe detect if the user has dark theme in osx enabled and display the appropriate theme for the website. Maybe we could use [this](https://css-tricks.com/dark-modes-with-css/) for that.

How was your plan to implement the website? With plain HTML and CSS or something like jekyll?

**Comment by 4goodapp** [comment]
> They look awesome!
Cool, Glad you like it... didn't have much time to do it...

> Maybe we could use this for that.
Woaaw, This looks awsome, didn't know we can have this. But yeah, why not.

> How was your plan to implement the website? With plain HTML and CSS or something like jekyll?

I think a simple HTML one will work as it's a really simple site.

-----

I'll try to code it tonight or tomorrow if that's OK.

**Comment by D0miH** [comment]
Perfekt! You can just submit a PR that addresses https://github.com/iglance/iglance.github.io/issues/1 at the [iglance.github.io](https://github.com/iglance/iglance.github.io) repository.
