### ISSUE TITLE
It stops updating metrics after my Mac wakes from sleep

### ISSUE THREAD

**Issue by uqix** [iglance/iGlance#75]
**Desktop (please complete the following information):**
 - OS: 10.15.2 (19C57)
 - Version of the app: 1.4.3

**Comment by D0miH** [comment]
Hey @uqix,
thanks for reporting the issue. 

To narrow down the issue here some questions:
- Do you have `Check for updates when waking up` activated?
- Are you connected to the internet when the problem appears? Or are you completely offline?

**Comment by uqix** [comment]
@D0miH 

> Do you have Check for updates when waking up activated?
Yes, this option is activated

> Are you connected to the internet when the problem appears? Or are you completely offline?
Yes, the internet is available

**Comment by uqix** [comment]
OMG! I just realized the update-check needs access to GitHub content  which may be f*king blocked by CGW

**Comment by uqix** [comment]
@D0miH May be we could just give up the update-check instead of malfunction if the network is unavailable?

**Comment by D0miH** [comment]
Glad you resolved the issue :)

Yeah, the current way of checking for updates is ... lets say suboptimal. However with version 2.0 this will be no problem anymore since [Sparkle](https://sparkle-project.org) will be used (see issue #62).

**Comment by uqix** [comment]
Thanks! Looking forward to it!

**Comment by uqix** [comment]
@D0miH The problem reoccurs  when Mac wakes from totally sleep for like 30 mins,
Here is my config screenshot:
![image](https://user-images.githubusercontent.com/10142314/73634442-2ce0e480-469c-11ea-8e46-e94bd5c5bd3e.png)
