### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by RobertasMurnikovas** [iglance/iGlance#77]
Every once in a while the app just freezes. Sometimes it happens while pc is being asleep or just randomly I notice that the cpu/mem graphs freezed and have to restart the app. Could someone look into this, sorry, but I don't have any specific errors to output.

iGlance 1.4.3

macOS 10.15.3 19D76 x86_64
Kernel: 19.3.0
CPU: Intel i5-5257U (4) @ 2.70GHz
GPU: Intel Iris Graphics 6100

**Comment by D0miH** [comment]
Hey @RobertasMurnikovas,
sorry you are experiencing stability issues. 
As you can imagine it is hard to debug without any specific evidence what went wrong. To fix this I am going to release a new Version in the next few days where the whole app is re-written to be more stable and has substantially more logging info. This will help me in the future to debug issues like yours.

 I hope you can bear it until the next version.

**Comment by RobertasMurnikovas** [comment]
Great, will wait for the new version, thanks for this quick replay!:)
