### ISSUE TITLE
App is not starting

### ISSUE THREAD

**Issue by D0miH** [iglance/iGlance#82]
**Describe the bug**
On a Macbook Pro from 2015 the app is not starting.

**To Reproduce**
1. Download the latest release
2. Try to start the app
3. The app is not starting

**Expected behavior**
The app should start.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Version of the app: 2.0

**Comment by jsoh** [comment]
The latest `2.0` release does not start on macOS 10.15.4 either. I also have the MacBook Pro (Retina, 15-inch, Mid 2015).

I have attempted installation with `brew cask install iglance` and manual download. Neither have worked for me.

**Comment by TimeDoctor** [comment]
I'm on 10.14.6 and have a similar issue. Crashlog from console:

[iGlance_2020-03-28-183917_idalek.crash.txt](https://github.com/iglance/iGlance/files/4398289/iGlance_2020-03-28-183917_idalek.crash.txt)

**Comment by D0miH** [comment]
Hey guys,

thanks for the feedback. 
This bug should now be fixed with 11f9a70f7bca4bb7d4d5e42b76e55b5da2f6ff1d and b949bc01f33922ff267028a2a6f1f110f8f98cf1.
The app is now launching on my Macbook Pro 2015. 
Could you please try to install the newest version and check whether the app is launching on yours too?

Cheers

**Comment by jsoh** [comment]
@D0miH Confirmed to be working. I downloaded the latest version 2.0.2 and it starts as expected. 

Thank you!

**Comment by D0miH** [comment]
Nice👍🏼
