### ISSUE TITLE
Option to change menubar font

### ISSUE THREAD

**Issue by tech189** [iglance/iGlance#92]
**Is your feature request related to a problem? Please describe.**
It would be nice to change the font for the text on the menubar!

**Describe the solution you'd like**
A menu in the settings to change the font

**Describe alternatives you've considered**
Could switch back to a version before 2.0, when the font used was the system font so it matched perfectly with the default time and battery percentage menubar items!

**Additional context**
Here's how it looked previously:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/10728085/77905279-e237af00-727d-11ea-9cfe-23eba19c2267.png">

**Comment by D0miH** [comment]
Hi @tech189, 
thanks for the feedback. Indeed this is a point I didn't think about when choosing the font. I thought the font I chose was the system font, but when looking closely I can see that it is not. 
I will try to find a way that the system font (as well as the system font size) is used to render the text in the menu bar.
