### ISSUE TITLE
Window selection menu item under Diagnostics

### ISSUE THREAD

**Issue by tech189** [iglance/iGlance#93]
**Describe the bug**
The window selection menu item is found both under Window and Diagnostics.

**To Reproduce**
1. Go to menubar
2. Click on iGlance
3. Click on Settings
4. Now dashboard is open, look at top left of screen
5. Click on Window, see "✔️ iGlance" (this is in the correct place)
6. Click on Diagnostics, see "✔️ iGlance" (this should not be here too)

**Expected behavior**
"✔️ iGlance" should only be under the Window menu

**Screenshots**
<img width="534" alt="Screenshot 2020-03-30 at 13 09 13" src="https://user-images.githubusercontent.com/10728085/77910866-c20ced80-7287-11ea-9b91-f5949fec16a5.png">
<img width="558" alt="Screenshot 2020-03-30 at 13 09 18" src="https://user-images.githubusercontent.com/10728085/77910864-c0dbc080-7287-11ea-90f9-445eab4601aa.png">

**Desktop (please complete the following information):**
 - Version of the app: 2.0.3

**Comment by D0miH** [comment]
Hi @tech189, 

thanks for pointing it out. You seem to examine the app very thoroughly 👀😉. I would have never catched that mistake👍🏼

**Comment by tech189** [comment]
Haha no problem, hopefully if you fix that it will remove the greyed out "Move Window to Left/Right Side of Screen" entries from the Diagnostics menu too 😄
