### ISSUE TITLE
Temperature indicator shows -1º

### ISSUE THREAD

**Issue by enthea** [iglance/iGlance#94]
**Describe the bug**
Temperature indicator shows -1º

**To Reproduce**
Start iGlance. Showed -1. Changed setting from C to F. Still showed -1.

**Expected behavior**
I expect the temperature indicator to show the current temperature.

**Screenshots**
![image](https://user-images.githubusercontent.com/62910825/77964197-ebd00f80-729b-11ea-9e08-b85e9cadd38f.png)

**Desktop (please complete the following information):**
 - OS: macos 10.13.6
 - Version of the app: 2.0.3
 - Hardware: MacBookPro8,3 (17-inch, Late 2011)

**Additional context**

**Comment by D0miH** [comment]
Hey @enthea, 
thanks for reporting the bug. To investigate the issue I need more information.
Could you upload the latest log file in a comment in this issue here? You can find the log files of iGlance under `~/Library/Logs/iGlance`.

**Comment by khorolets** [comment]
Hi there, the same issue, attaching my log

(iMac 2019, fresh Catalina 10.15.4)

[io.github.iglance.iGlance 2020-03-31--08-33-52-417.txt](https://github.com/iglance/iGlance/files/4407701/io.github.iglance.iGlance.2020-03-31--08-33-52-417.txt)

**Comment by D0miH** [comment]
Hey @khorolets, @enthea,

so i think I figured it out what caused the bug. It should be fixed with the next update :)

**Comment by khorolets** [comment]
@D0miH nice to hear that! Great app btw, thank you for your work!
